/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AlmanacRouteImport } from './routes/almanac'
import { Route as CommunityRouteImport } from './routes/community'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as DownloadRouteImport } from './routes/download'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as GalleryRouteImport } from './routes/gallery'
import { Route as LeaderboardRouteImport } from './routes/leaderboard'
import { Route as LeaderboardsRouteImport } from './routes/leaderboards'
import { Route as LoginRouteImport } from './routes/login'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as ShopRouteImport } from './routes/shop'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AdminAlmanacRouteImport } from './routes/admin.almanac'
import { Route as AdminBugsRouteImport } from './routes/admin.bugs'
import { Route as AdminFaqRouteImport } from './routes/admin.faq'
import { Route as AdminGalleryRouteImport } from './routes/admin.gallery'
import { Route as AdminIntegrationRouteImport } from './routes/admin.integration'
import { Route as AdminLeaderboardRouteImport } from './routes/admin.leaderboard'
import { Route as AdminLoginRouteImport } from './routes/admin.login'
import { Route as AdminMessagesRouteImport } from './routes/admin.messages'
import { Route as AdminNewsRouteImport } from './routes/admin.news'
import { Route as AdminPlayersRouteImport } from './routes/admin.players'
import { Route as AdminProductsRouteImport } from './routes/admin.products'
import { Route as AdminReleasesRouteImport } from './routes/admin.releases'
import { Route as AdminSettingsRouteImport } from './routes/admin.settings'
import { Route as AdminTransactionsRouteImport } from './routes/admin.transactions'
import { Route as CommunityIndexRouteImport } from './routes/community.index'
import { Route as CommunityGalleryRouteImport } from './routes/community.gallery'
import { Route as DashboardIndexRouteImport } from './routes/dashboard.index'
import { Route as DashboardAchievementsRouteImport } from './routes/dashboard.achievements'
import { Route as DashboardAlmanacRouteImport } from './routes/dashboard.almanac'
import { Route as DashboardLeaderboardsRouteImport } from './routes/dashboard.leaderboards'
import { Route as DashboardMessagesRouteImport } from './routes/dashboard.messages'
import { Route as DashboardProfileRouteImport } from './routes/dashboard.profile'
import { Route as DashboardSettingsRouteImport } from './routes/dashboard.settings'
import { Route as DashboardShopRouteImport } from './routes/dashboard.shop'
import { Route as DashboardTransactionsRouteImport } from './routes/dashboard.transactions'
import { Route as PaymentCancelRouteImport } from './routes/payment.cancel'
import { Route as PaymentSuccessRouteImport } from './routes/payment.success'
import { Route as UpdatesIndexRouteImport } from './routes/updates.index'
import { Route as UpdatesSlugRouteImport } from './routes/updates.$slug'
import { Route as CommunityNewsIndexRouteImport } from './routes/community.news.index'
import { Route as CommunityNewsSlugRouteImport } from './routes/community.news.$slug'
import { Route as DashboardPaymentCancelRouteImport } from './routes/dashboard.payment.cancel'
import { Route as DashboardPaymentSuccessRouteImport } from './routes/dashboard.payment.success'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AlmanacRoute = AlmanacRouteImport.update({
  id: '/almanac',
  path: '/almanac',
  getParentRoute: () => rootRouteImport,
} as any)
const CommunityRoute = CommunityRouteImport.update({
  id: '/community',
  path: '/community',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const DownloadRoute = DownloadRouteImport.update({
  id: '/download',
  path: '/download',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const GalleryRoute = GalleryRouteImport.update({
  id: '/gallery',
  path: '/gallery',
  getParentRoute: () => rootRouteImport,
} as any)
const LeaderboardRoute = LeaderboardRouteImport.update({
  id: '/leaderboard',
  path: '/leaderboard',
  getParentRoute: () => rootRouteImport,
} as any)
const LeaderboardsRoute = LeaderboardsRouteImport.update({
  id: '/leaderboards',
  path: '/leaderboards',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopRoute = ShopRouteImport.update({
  id: '/shop',
  path: '/shop',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAlmanacRoute = AdminAlmanacRouteImport.update({
  id: '/almanac',
  path: '/almanac',
  getParentRoute: () => AdminRoute,
} as any)
const AdminBugsRoute = AdminBugsRouteImport.update({
  id: '/bugs',
  path: '/bugs',
  getParentRoute: () => AdminRoute,
} as any)
const AdminFaqRoute = AdminFaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => AdminRoute,
} as any)
const AdminGalleryRoute = AdminGalleryRouteImport.update({
  id: '/gallery',
  path: '/gallery',
  getParentRoute: () => AdminRoute,
} as any)
const AdminIntegrationRoute = AdminIntegrationRouteImport.update({
  id: '/integration',
  path: '/integration',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLeaderboardRoute = AdminLeaderboardRouteImport.update({
  id: '/leaderboard',
  path: '/leaderboard',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AdminRoute,
} as any)
const AdminMessagesRoute = AdminMessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => AdminRoute,
} as any)
const AdminNewsRoute = AdminNewsRouteImport.update({
  id: '/news',
  path: '/news',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPlayersRoute = AdminPlayersRouteImport.update({
  id: '/players',
  path: '/players',
  getParentRoute: () => AdminRoute,
} as any)
const AdminProductsRoute = AdminProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => AdminRoute,
} as any)
const AdminReleasesRoute = AdminReleasesRouteImport.update({
  id: '/releases',
  path: '/releases',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminRoute,
} as any)
const AdminTransactionsRoute = AdminTransactionsRouteImport.update({
  id: '/transactions',
  path: '/transactions',
  getParentRoute: () => AdminRoute,
} as any)
const CommunityIndexRoute = CommunityIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CommunityRoute,
} as any)
const CommunityGalleryRoute = CommunityGalleryRouteImport.update({
  id: '/gallery',
  path: '/gallery',
  getParentRoute: () => CommunityRoute,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardAchievementsRoute = DashboardAchievementsRouteImport.update({
  id: '/achievements',
  path: '/achievements',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardAlmanacRoute = DashboardAlmanacRouteImport.update({
  id: '/almanac',
  path: '/almanac',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardLeaderboardsRoute = DashboardLeaderboardsRouteImport.update({
  id: '/leaderboards',
  path: '/leaderboards',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardMessagesRoute = DashboardMessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardProfileRoute = DashboardProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardSettingsRoute = DashboardSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardShopRoute = DashboardShopRouteImport.update({
  id: '/shop',
  path: '/shop',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardTransactionsRoute = DashboardTransactionsRouteImport.update({
  id: '/transactions',
  path: '/transactions',
  getParentRoute: () => DashboardRoute,
} as any)
const PaymentCancelRoute = PaymentCancelRouteImport.update({
  id: '/payment/cancel',
  path: '/payment/cancel',
  getParentRoute: () => rootRouteImport,
} as any)
const PaymentSuccessRoute = PaymentSuccessRouteImport.update({
  id: '/payment/success',
  path: '/payment/success',
  getParentRoute: () => rootRouteImport,
} as any)
const UpdatesIndexRoute = UpdatesIndexRouteImport.update({
  id: '/updates/',
  path: '/updates/',
  getParentRoute: () => rootRouteImport,
} as any)
const UpdatesSlugRoute = UpdatesSlugRouteImport.update({
  id: '/updates/$slug',
  path: '/updates/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const CommunityNewsIndexRoute = CommunityNewsIndexRouteImport.update({
  id: '/news/',
  path: '/news/',
  getParentRoute: () => CommunityRoute,
} as any)
const CommunityNewsSlugRoute = CommunityNewsSlugRouteImport.update({
  id: '/news/$slug',
  path: '/news/$slug',
  getParentRoute: () => CommunityRoute,
} as any)
const DashboardPaymentCancelRoute = DashboardPaymentCancelRouteImport.update({
  id: '/payment/cancel',
  path: '/payment/cancel',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardPaymentSuccessRoute = DashboardPaymentSuccessRouteImport.update({
  id: '/payment/success',
  path: '/payment/success',
  getParentRoute: () => DashboardRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/almanac': typeof AlmanacRoute
  '/community': typeof CommunityRouteWithChildren
  '/contact': typeof ContactRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/download': typeof DownloadRoute
  '/faq': typeof FaqRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/gallery': typeof GalleryRoute
  '/leaderboard': typeof LeaderboardRoute
  '/leaderboards': typeof LeaderboardsRoute
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/shop': typeof ShopRoute
  '/signup': typeof SignupRoute
  '/terms': typeof TermsRoute
  '/admin/almanac': typeof AdminAlmanacRoute
  '/admin/bugs': typeof AdminBugsRoute
  '/admin/faq': typeof AdminFaqRoute
  '/admin/gallery': typeof AdminGalleryRoute
  '/admin/integration': typeof AdminIntegrationRoute
  '/admin/leaderboard': typeof AdminLeaderboardRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/messages': typeof AdminMessagesRoute
  '/admin/news': typeof AdminNewsRoute
  '/admin/players': typeof AdminPlayersRoute
  '/admin/products': typeof AdminProductsRoute
  '/admin/releases': typeof AdminReleasesRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/transactions': typeof AdminTransactionsRoute
  '/community/gallery': typeof CommunityGalleryRoute
  '/dashboard/achievements': typeof DashboardAchievementsRoute
  '/dashboard/almanac': typeof DashboardAlmanacRoute
  '/dashboard/leaderboards': typeof DashboardLeaderboardsRoute
  '/dashboard/messages': typeof DashboardMessagesRoute
  '/dashboard/profile': typeof DashboardProfileRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard/shop': typeof DashboardShopRoute
  '/dashboard/transactions': typeof DashboardTransactionsRoute
  '/payment/cancel': typeof PaymentCancelRoute
  '/payment/success': typeof PaymentSuccessRoute
  '/updates/$slug': typeof UpdatesSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/community/': typeof CommunityIndexRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/updates/': typeof UpdatesIndexRoute
  '/community/news/$slug': typeof CommunityNewsSlugRoute
  '/dashboard/payment/cancel': typeof DashboardPaymentCancelRoute
  '/dashboard/payment/success': typeof DashboardPaymentSuccessRoute
  '/community/news/': typeof CommunityNewsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/almanac': typeof AlmanacRoute
  '/contact': typeof ContactRoute
  '/download': typeof DownloadRoute
  '/faq': typeof FaqRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/gallery': typeof GalleryRoute
  '/leaderboard': typeof LeaderboardRoute
  '/leaderboards': typeof LeaderboardsRoute
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/shop': typeof ShopRoute
  '/signup': typeof SignupRoute
  '/terms': typeof TermsRoute
  '/admin/almanac': typeof AdminAlmanacRoute
  '/admin/bugs': typeof AdminBugsRoute
  '/admin/faq': typeof AdminFaqRoute
  '/admin/gallery': typeof AdminGalleryRoute
  '/admin/integration': typeof AdminIntegrationRoute
  '/admin/leaderboard': typeof AdminLeaderboardRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/messages': typeof AdminMessagesRoute
  '/admin/news': typeof AdminNewsRoute
  '/admin/players': typeof AdminPlayersRoute
  '/admin/products': typeof AdminProductsRoute
  '/admin/releases': typeof AdminReleasesRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/transactions': typeof AdminTransactionsRoute
  '/community/gallery': typeof CommunityGalleryRoute
  '/dashboard/achievements': typeof DashboardAchievementsRoute
  '/dashboard/almanac': typeof DashboardAlmanacRoute
  '/dashboard/leaderboards': typeof DashboardLeaderboardsRoute
  '/dashboard/messages': typeof DashboardMessagesRoute
  '/dashboard/profile': typeof DashboardProfileRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard/shop': typeof DashboardShopRoute
  '/dashboard/transactions': typeof DashboardTransactionsRoute
  '/payment/cancel': typeof PaymentCancelRoute
  '/payment/success': typeof PaymentSuccessRoute
  '/updates/$slug': typeof UpdatesSlugRoute
  '/admin': typeof AdminIndexRoute
  '/community': typeof CommunityIndexRoute
  '/dashboard': typeof DashboardIndexRoute
  '/updates': typeof UpdatesIndexRoute
  '/community/news/$slug': typeof CommunityNewsSlugRoute
  '/dashboard/payment/cancel': typeof DashboardPaymentCancelRoute
  '/dashboard/payment/success': typeof DashboardPaymentSuccessRoute
  '/community/news': typeof CommunityNewsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/almanac': typeof AlmanacRoute
  '/community': typeof CommunityRouteWithChildren
  '/contact': typeof ContactRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/download': typeof DownloadRoute
  '/faq': typeof FaqRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/gallery': typeof GalleryRoute
  '/leaderboard': typeof LeaderboardRoute
  '/leaderboards': typeof LeaderboardsRoute
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/shop': typeof ShopRoute
  '/signup': typeof SignupRoute
  '/terms': typeof TermsRoute
  '/admin/almanac': typeof AdminAlmanacRoute
  '/admin/bugs': typeof AdminBugsRoute
  '/admin/faq': typeof AdminFaqRoute
  '/admin/gallery': typeof AdminGalleryRoute
  '/admin/integration': typeof AdminIntegrationRoute
  '/admin/leaderboard': typeof AdminLeaderboardRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/messages': typeof AdminMessagesRoute
  '/admin/news': typeof AdminNewsRoute
  '/admin/players': typeof AdminPlayersRoute
  '/admin/products': typeof AdminProductsRoute
  '/admin/releases': typeof AdminReleasesRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/transactions': typeof AdminTransactionsRoute
  '/community/gallery': typeof CommunityGalleryRoute
  '/dashboard/achievements': typeof DashboardAchievementsRoute
  '/dashboard/almanac': typeof DashboardAlmanacRoute
  '/dashboard/leaderboards': typeof DashboardLeaderboardsRoute
  '/dashboard/messages': typeof DashboardMessagesRoute
  '/dashboard/profile': typeof DashboardProfileRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard/shop': typeof DashboardShopRoute
  '/dashboard/transactions': typeof DashboardTransactionsRoute
  '/payment/cancel': typeof PaymentCancelRoute
  '/payment/success': typeof PaymentSuccessRoute
  '/updates/$slug': typeof UpdatesSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/community/': typeof CommunityIndexRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/updates/': typeof UpdatesIndexRoute
  '/community/news/$slug': typeof CommunityNewsSlugRoute
  '/dashboard/payment/cancel': typeof DashboardPaymentCancelRoute
  '/dashboard/payment/success': typeof DashboardPaymentSuccessRoute
  '/community/news/': typeof CommunityNewsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/admin'
    | '/almanac'
    | '/community'
    | '/contact'
    | '/dashboard'
    | '/download'
    | '/faq'
    | '/forgot-password'
    | '/gallery'
    | '/leaderboard'
    | '/leaderboards'
    | '/login'
    | '/privacy'
    | '/reset-password'
    | '/shop'
    | '/signup'
    | '/terms'
    | '/admin/almanac'
    | '/admin/bugs'
    | '/admin/faq'
    | '/admin/gallery'
    | '/admin/integration'
    | '/admin/leaderboard'
    | '/admin/login'
    | '/admin/messages'
    | '/admin/news'
    | '/admin/players'
    | '/admin/products'
    | '/admin/releases'
    | '/admin/settings'
    | '/admin/transactions'
    | '/community/gallery'
    | '/dashboard/achievements'
    | '/dashboard/almanac'
    | '/dashboard/leaderboards'
    | '/dashboard/messages'
    | '/dashboard/profile'
    | '/dashboard/settings'
    | '/dashboard/shop'
    | '/dashboard/transactions'
    | '/payment/cancel'
    | '/payment/success'
    | '/updates/$slug'
    | '/admin/'
    | '/community/'
    | '/dashboard/'
    | '/updates/'
    | '/community/news/$slug'
    | '/dashboard/payment/cancel'
    | '/dashboard/payment/success'
    | '/community/news/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/almanac'
    | '/contact'
    | '/download'
    | '/faq'
    | '/forgot-password'
    | '/gallery'
    | '/leaderboard'
    | '/leaderboards'
    | '/login'
    | '/privacy'
    | '/reset-password'
    | '/shop'
    | '/signup'
    | '/terms'
    | '/admin/almanac'
    | '/admin/bugs'
    | '/admin/faq'
    | '/admin/gallery'
    | '/admin/integration'
    | '/admin/leaderboard'
    | '/admin/login'
    | '/admin/messages'
    | '/admin/news'
    | '/admin/players'
    | '/admin/products'
    | '/admin/releases'
    | '/admin/settings'
    | '/admin/transactions'
    | '/community/gallery'
    | '/dashboard/achievements'
    | '/dashboard/almanac'
    | '/dashboard/leaderboards'
    | '/dashboard/messages'
    | '/dashboard/profile'
    | '/dashboard/settings'
    | '/dashboard/shop'
    | '/dashboard/transactions'
    | '/payment/cancel'
    | '/payment/success'
    | '/updates/$slug'
    | '/admin'
    | '/community'
    | '/dashboard'
    | '/updates'
    | '/community/news/$slug'
    | '/dashboard/payment/cancel'
    | '/dashboard/payment/success'
    | '/community/news'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/admin'
    | '/almanac'
    | '/community'
    | '/contact'
    | '/dashboard'
    | '/download'
    | '/faq'
    | '/forgot-password'
    | '/gallery'
    | '/leaderboard'
    | '/leaderboards'
    | '/login'
    | '/privacy'
    | '/reset-password'
    | '/shop'
    | '/signup'
    | '/terms'
    | '/admin/almanac'
    | '/admin/bugs'
    | '/admin/faq'
    | '/admin/gallery'
    | '/admin/integration'
    | '/admin/leaderboard'
    | '/admin/login'
    | '/admin/messages'
    | '/admin/news'
    | '/admin/players'
    | '/admin/products'
    | '/admin/releases'
    | '/admin/settings'
    | '/admin/transactions'
    | '/community/gallery'
    | '/dashboard/achievements'
    | '/dashboard/almanac'
    | '/dashboard/leaderboards'
    | '/dashboard/messages'
    | '/dashboard/profile'
    | '/dashboard/settings'
    | '/dashboard/shop'
    | '/dashboard/transactions'
    | '/payment/cancel'
    | '/payment/success'
    | '/updates/$slug'
    | '/admin/'
    | '/community/'
    | '/dashboard/'
    | '/updates/'
    | '/community/news/$slug'
    | '/dashboard/payment/cancel'
    | '/dashboard/payment/success'
    | '/community/news/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AdminRoute: typeof AdminRouteWithChildren
  AlmanacRoute: typeof AlmanacRoute
  CommunityRoute: typeof CommunityRouteWithChildren
  ContactRoute: typeof ContactRoute
  DashboardRoute: typeof DashboardRouteWithChildren
  DownloadRoute: typeof DownloadRoute
  FaqRoute: typeof FaqRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  GalleryRoute: typeof GalleryRoute
  LeaderboardRoute: typeof LeaderboardRoute
  LeaderboardsRoute: typeof LeaderboardsRoute
  LoginRoute: typeof LoginRoute
  PrivacyRoute: typeof PrivacyRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  ShopRoute: typeof ShopRoute
  SignupRoute: typeof SignupRoute
  TermsRoute: typeof TermsRoute
  PaymentCancelRoute: typeof PaymentCancelRoute
  PaymentSuccessRoute: typeof PaymentSuccessRoute
  UpdatesSlugRoute: typeof UpdatesSlugRoute
  UpdatesIndexRoute: typeof UpdatesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/almanac': {
      id: '/almanac'
      path: '/almanac'
      fullPath: '/almanac'
      preLoaderRoute: typeof AlmanacRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/community': {
      id: '/community'
      path: '/community'
      fullPath: '/community'
      preLoaderRoute: typeof CommunityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/download': {
      id: '/download'
      path: '/download'
      fullPath: '/download'
      preLoaderRoute: typeof DownloadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gallery': {
      id: '/gallery'
      path: '/gallery'
      fullPath: '/gallery'
      preLoaderRoute: typeof GalleryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leaderboard': {
      id: '/leaderboard'
      path: '/leaderboard'
      fullPath: '/leaderboard'
      preLoaderRoute: typeof LeaderboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leaderboards': {
      id: '/leaderboards'
      path: '/leaderboards'
      fullPath: '/leaderboards'
      preLoaderRoute: typeof LeaderboardsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shop': {
      id: '/shop'
      path: '/shop'
      fullPath: '/shop'
      preLoaderRoute: typeof ShopRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/almanac': {
      id: '/admin/almanac'
      path: '/almanac'
      fullPath: '/admin/almanac'
      preLoaderRoute: typeof AdminAlmanacRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/bugs': {
      id: '/admin/bugs'
      path: '/bugs'
      fullPath: '/admin/bugs'
      preLoaderRoute: typeof AdminBugsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/faq': {
      id: '/admin/faq'
      path: '/faq'
      fullPath: '/admin/faq'
      preLoaderRoute: typeof AdminFaqRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/gallery': {
      id: '/admin/gallery'
      path: '/gallery'
      fullPath: '/admin/gallery'
      preLoaderRoute: typeof AdminGalleryRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/integration': {
      id: '/admin/integration'
      path: '/integration'
      fullPath: '/admin/integration'
      preLoaderRoute: typeof AdminIntegrationRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/leaderboard': {
      id: '/admin/leaderboard'
      path: '/leaderboard'
      fullPath: '/admin/leaderboard'
      preLoaderRoute: typeof AdminLeaderboardRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/messages': {
      id: '/admin/messages'
      path: '/messages'
      fullPath: '/admin/messages'
      preLoaderRoute: typeof AdminMessagesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/news': {
      id: '/admin/news'
      path: '/news'
      fullPath: '/admin/news'
      preLoaderRoute: typeof AdminNewsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/players': {
      id: '/admin/players'
      path: '/players'
      fullPath: '/admin/players'
      preLoaderRoute: typeof AdminPlayersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/products': {
      id: '/admin/products'
      path: '/products'
      fullPath: '/admin/products'
      preLoaderRoute: typeof AdminProductsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/releases': {
      id: '/admin/releases'
      path: '/releases'
      fullPath: '/admin/releases'
      preLoaderRoute: typeof AdminReleasesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/transactions': {
      id: '/admin/transactions'
      path: '/transactions'
      fullPath: '/admin/transactions'
      preLoaderRoute: typeof AdminTransactionsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/community/': {
      id: '/community/'
      path: '/'
      fullPath: '/community/'
      preLoaderRoute: typeof CommunityIndexRouteImport
      parentRoute: typeof CommunityRoute
    }
    '/community/gallery': {
      id: '/community/gallery'
      path: '/gallery'
      fullPath: '/community/gallery'
      preLoaderRoute: typeof CommunityGalleryRouteImport
      parentRoute: typeof CommunityRoute
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/achievements': {
      id: '/dashboard/achievements'
      path: '/achievements'
      fullPath: '/dashboard/achievements'
      preLoaderRoute: typeof DashboardAchievementsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/almanac': {
      id: '/dashboard/almanac'
      path: '/almanac'
      fullPath: '/dashboard/almanac'
      preLoaderRoute: typeof DashboardAlmanacRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/leaderboards': {
      id: '/dashboard/leaderboards'
      path: '/leaderboards'
      fullPath: '/dashboard/leaderboards'
      preLoaderRoute: typeof DashboardLeaderboardsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/messages': {
      id: '/dashboard/messages'
      path: '/messages'
      fullPath: '/dashboard/messages'
      preLoaderRoute: typeof DashboardMessagesRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/profile': {
      id: '/dashboard/profile'
      path: '/profile'
      fullPath: '/dashboard/profile'
      preLoaderRoute: typeof DashboardProfileRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/settings': {
      id: '/dashboard/settings'
      path: '/settings'
      fullPath: '/dashboard/settings'
      preLoaderRoute: typeof DashboardSettingsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/shop': {
      id: '/dashboard/shop'
      path: '/shop'
      fullPath: '/dashboard/shop'
      preLoaderRoute: typeof DashboardShopRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/transactions': {
      id: '/dashboard/transactions'
      path: '/transactions'
      fullPath: '/dashboard/transactions'
      preLoaderRoute: typeof DashboardTransactionsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/payment/cancel': {
      id: '/payment/cancel'
      path: '/payment/cancel'
      fullPath: '/payment/cancel'
      preLoaderRoute: typeof PaymentCancelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/payment/success': {
      id: '/payment/success'
      path: '/payment/success'
      fullPath: '/payment/success'
      preLoaderRoute: typeof PaymentSuccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/updates/': {
      id: '/updates/'
      path: '/updates'
      fullPath: '/updates/'
      preLoaderRoute: typeof UpdatesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/updates/$slug': {
      id: '/updates/$slug'
      path: '/updates/$slug'
      fullPath: '/updates/$slug'
      preLoaderRoute: typeof UpdatesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/community/news/': {
      id: '/community/news/'
      path: '/news'
      fullPath: '/community/news/'
      preLoaderRoute: typeof CommunityNewsIndexRouteImport
      parentRoute: typeof CommunityRoute
    }
    '/community/news/$slug': {
      id: '/community/news/$slug'
      path: '/news/$slug'
      fullPath: '/community/news/$slug'
      preLoaderRoute: typeof CommunityNewsSlugRouteImport
      parentRoute: typeof CommunityRoute
    }
    '/dashboard/payment/cancel': {
      id: '/dashboard/payment/cancel'
      path: '/payment/cancel'
      fullPath: '/dashboard/payment/cancel'
      preLoaderRoute: typeof DashboardPaymentCancelRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/payment/success': {
      id: '/dashboard/payment/success'
      path: '/payment/success'
      fullPath: '/dashboard/payment/success'
      preLoaderRoute: typeof DashboardPaymentSuccessRouteImport
      parentRoute: typeof DashboardRoute
    }
  }
}

interface AdminRouteChildren {
  AdminAlmanacRoute: typeof AdminAlmanacRoute
  AdminBugsRoute: typeof AdminBugsRoute
  AdminFaqRoute: typeof AdminFaqRoute
  AdminGalleryRoute: typeof AdminGalleryRoute
  AdminIntegrationRoute: typeof AdminIntegrationRoute
  AdminLeaderboardRoute: typeof AdminLeaderboardRoute
  AdminLoginRoute: typeof AdminLoginRoute
  AdminMessagesRoute: typeof AdminMessagesRoute
  AdminNewsRoute: typeof AdminNewsRoute
  AdminPlayersRoute: typeof AdminPlayersRoute
  AdminProductsRoute: typeof AdminProductsRoute
  AdminReleasesRoute: typeof AdminReleasesRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminTransactionsRoute: typeof AdminTransactionsRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAlmanacRoute: AdminAlmanacRoute,
  AdminBugsRoute: AdminBugsRoute,
  AdminFaqRoute: AdminFaqRoute,
  AdminGalleryRoute: AdminGalleryRoute,
  AdminIntegrationRoute: AdminIntegrationRoute,
  AdminLeaderboardRoute: AdminLeaderboardRoute,
  AdminLoginRoute: AdminLoginRoute,
  AdminMessagesRoute: AdminMessagesRoute,
  AdminNewsRoute: AdminNewsRoute,
  AdminPlayersRoute: AdminPlayersRoute,
  AdminProductsRoute: AdminProductsRoute,
  AdminReleasesRoute: AdminReleasesRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminTransactionsRoute: AdminTransactionsRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface CommunityRouteChildren {
  CommunityGalleryRoute: typeof CommunityGalleryRoute
  CommunityIndexRoute: typeof CommunityIndexRoute
  CommunityNewsSlugRoute: typeof CommunityNewsSlugRoute
  CommunityNewsIndexRoute: typeof CommunityNewsIndexRoute
}

const CommunityRouteChildren: CommunityRouteChildren = {
  CommunityGalleryRoute: CommunityGalleryRoute,
  CommunityIndexRoute: CommunityIndexRoute,
  CommunityNewsSlugRoute: CommunityNewsSlugRoute,
  CommunityNewsIndexRoute: CommunityNewsIndexRoute,
}

const CommunityRouteWithChildren = CommunityRoute._addFileChildren(
  CommunityRouteChildren,
)

interface DashboardRouteChildren {
  DashboardAchievementsRoute: typeof DashboardAchievementsRoute
  DashboardAlmanacRoute: typeof DashboardAlmanacRoute
  DashboardLeaderboardsRoute: typeof DashboardLeaderboardsRoute
  DashboardMessagesRoute: typeof DashboardMessagesRoute
  DashboardProfileRoute: typeof DashboardProfileRoute
  DashboardSettingsRoute: typeof DashboardSettingsRoute
  DashboardShopRoute: typeof DashboardShopRoute
  DashboardTransactionsRoute: typeof DashboardTransactionsRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
  DashboardPaymentCancelRoute: typeof DashboardPaymentCancelRoute
  DashboardPaymentSuccessRoute: typeof DashboardPaymentSuccessRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardAchievementsRoute: DashboardAchievementsRoute,
  DashboardAlmanacRoute: DashboardAlmanacRoute,
  DashboardLeaderboardsRoute: DashboardLeaderboardsRoute,
  DashboardMessagesRoute: DashboardMessagesRoute,
  DashboardProfileRoute: DashboardProfileRoute,
  DashboardSettingsRoute: DashboardSettingsRoute,
  DashboardShopRoute: DashboardShopRoute,
  DashboardTransactionsRoute: DashboardTransactionsRoute,
  DashboardIndexRoute: DashboardIndexRoute,
  DashboardPaymentCancelRoute: DashboardPaymentCancelRoute,
  DashboardPaymentSuccessRoute: DashboardPaymentSuccessRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AdminRoute: AdminRouteWithChildren,
  AlmanacRoute: AlmanacRoute,
  CommunityRoute: CommunityRouteWithChildren,
  ContactRoute: ContactRoute,
  DashboardRoute: DashboardRouteWithChildren,
  DownloadRoute: DownloadRoute,
  FaqRoute: FaqRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  GalleryRoute: GalleryRoute,
  LeaderboardRoute: LeaderboardRoute,
  LeaderboardsRoute: LeaderboardsRoute,
  LoginRoute: LoginRoute,
  PrivacyRoute: PrivacyRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  ShopRoute: ShopRoute,
  SignupRoute: SignupRoute,
  TermsRoute: TermsRoute,
  PaymentCancelRoute: PaymentCancelRoute,
  PaymentSuccessRoute: PaymentSuccessRoute,
  UpdatesSlugRoute: UpdatesSlugRoute,
  UpdatesIndexRoute: UpdatesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
